ktor:
  security:
    ssl:
      keyStore: "keystore.jks"
      keyAlias: "sampleAlias"
      keyStorePassword: "foobar"
      privateKeyPassword: "foobar"
  deployment:
    port: 8080
    sslPort: 8444
  application:
    modules:
      - com.katemedia.com.katemedia.MainKt.module